### ISSUE TITLE
apt-get upgrade in base image?

### ISSUE THREAD

**Issue by fredclausen** [sdr-enthusiasts/docker-baseimage#30]
In the future I imagine we'll be rebuilding the images once a month, when the upstream `-slim` image is updated, but is there any harm in running `apt-get upgrade`? I figure it's worth just double-checking we are fully up to date when we build the image, and if we have reason to kick off an interim build then it'll capture any updates.

**Comment by kx1t** [comment]
I like this, even though it may make your base image layer a bit bigger. The size increase will  be temporarily, because when the base image updates, any subsequent `apt upgrade ` would pull in almost nothing.

**Comment by mikenye** [comment]
It used to be bad practice to do this, hadolint used to tell you off. 

However, it looks like this advice has changed:

https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
